version: '3.9'
services:
  app:
    build: .docker/php
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data:rw
